export const ErrorCodeEnum = {
  // Authentication & Authorization Errors
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_UNAUTHORIZED_ACCESS: 'AUTH_UNAUTHORIZED_ACCESS',

  ACCESS_UNAUTHORIZED: 'ACCESS_UNAUTHORIZED',
  ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',

  // Resource & Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  // System Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
